with open("src/App.tsx", "r") as f:
    content = f.read()

content = content.replace("unsubs.push(onSnapshot(challengesQuery, (snapshot) => {\n            const challenges = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));\n            if (challenges.length > 0) {\n              // Get the oldest pending challenge\n              setIncomingChallenge(challenges[0]);\n            } else {\n              setIncomingChallenge(null);\n            }\n          });", "unsubs.push(onSnapshot(challengesQuery, (snapshot) => {\n            const challenges = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));\n            if (challenges.length > 0) {\n              // Get the oldest pending challenge\n              setIncomingChallenge(challenges[0]);\n            } else {\n              setIncomingChallenge(null);\n            }\n          }));")

content = content.replace("unsubs.push(onSnapshot(myChallengesQuery, (snapshot) => {\n            snapshot.docChanges().forEach(change => {\n              if (change.type === 'added') {\n                const data = change.doc.data();\n                if (data.gameId) {\n                  // The other person accepted and created the game!\n                  // Active game logic will automatically pick it up via unsubscribeGames.\n                  // Just clean up the challenge.\n                  const db = getDb();\n                  deleteDoc(doc(db, 'challenges', change.doc.id)).catch(console.error);\n                }\n              }\n            });\n          });", "unsubs.push(onSnapshot(myChallengesQuery, (snapshot) => {\n            snapshot.docChanges().forEach(change => {\n              if (change.type === 'added') {\n                const data = change.doc.data();\n                if (data.gameId) {\n                  // The other person accepted and created the game!\n                  // Active game logic will automatically pick it up via unsubscribeGames.\n                  // Just clean up the challenge.\n                  const db = getDb();\n                  deleteDoc(doc(db, 'challenges', change.doc.id)).catch(console.error);\n                }\n              }\n            });\n          }));")

content = content.replace("unsubs.push(onSnapshot(userRef, async (docSnap) => {\n            if (docSnap.exists()) {\n              const data = docSnap.data() as UserData;\n              setUserData(data);\n              \n              if (data.activeTheme && data.activeTheme !== themeManager.getTheme().id) {\n                themeManager.setTheme(data.activeTheme);\n              }\n              if (data.activeBackground && data.activeBackground !== backgroundManager.getBackground().id) {\n                backgroundManager.setBackground(data.activeBackground);\n              }\n            } else {\n              // Create user if not exists\n              const initialData: UserData = {\n                uid: firebaseUser.uid,\n                displayName: firebaseUser.displayName || 'Jogador',\n                hasSetNickname: false,\n                elo: 1000,\n                gamesPlayed: 0,\n                coins: 100\n              };\n              try {\n                await setDoc(userRef, initialData);\n              } catch (e) {\n                console.error(\"Error creating user document\", e);\n              }\n            }\n          });", "unsubs.push(onSnapshot(userRef, async (docSnap) => {\n            if (docSnap.exists()) {\n              const data = docSnap.data() as UserData;\n              setUserData(data);\n              \n              if (data.activeTheme && data.activeTheme !== themeManager.getTheme().id) {\n                themeManager.setTheme(data.activeTheme);\n              }\n              if (data.activeBackground && data.activeBackground !== backgroundManager.getBackground().id) {\n                backgroundManager.setBackground(data.activeBackground);\n              }\n            } else {\n              // Create user if not exists\n              const initialData: UserData = {\n                uid: firebaseUser.uid,\n                displayName: firebaseUser.displayName || 'Jogador',\n                hasSetNickname: false,\n                elo: 1000,\n                gamesPlayed: 0,\n                coins: 100\n              };\n              try {\n                await setDoc(userRef, initialData);\n              } catch (e) {\n                console.error(\"Error creating user document\", e);\n              }\n            }\n          }));")

content = content.replace("unsubs.push(onSnapshot(q, (snapshot) => {\n            const games = snapshot.docs.map(d => ({ id: d.id, ...d.data() } as GameData));\n            const active = games.find(g => g.status === 'playing');\n            \n            setActiveGame(prev => {\n              if (active) {\n                if (!prev) setActiveTab('play');\n                setComputerGameDifficulty(null); // Leave computer game if online match found\n                return active;\n              }\n              if (prev) {\n                const finishedGame = games.find(g => g.id === prev.id);\n                if (finishedGame && finishedGame.status !== 'playing') {\n                  return finishedGame;\n                }\n              }\n              return null;\n            });\n            setLoading(false);\n          });", "unsubs.push(onSnapshot(q, (snapshot) => {\n            const games = snapshot.docs.map(d => ({ id: d.id, ...d.data() } as GameData));\n            const active = games.find(g => g.status === 'playing');\n            \n            setActiveGame(prev => {\n              if (active) {\n                if (!prev) setActiveTab('play');\n                setComputerGameDifficulty(null); // Leave computer game if online match found\n                return active;\n              }\n              if (prev) {\n                const finishedGame = games.find(g => g.id === prev.id);\n                if (finishedGame && finishedGame.status !== 'playing') {\n                  return finishedGame;\n                }\n              }\n              return null;\n            });\n            setLoading(false);\n          }));")

with open("src/App.tsx", "w") as f:
    f.write(content)
